name: Download latest Maven build validation scripts
description: "Downloads the latest release of the build validation scripts for Maven"

inputs:
  token:
    description: "GitHub token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Download latest Maven build validation scripts
      run: |
        # Set curl general options
        curlOpts="--silent --fail --show-error --retry 3 --retry-delay 5 --location"

        # Set authorization header if needed
        if [ ! -z "${{ inputs.token }}" ]; then
          curlOpts="$curlOpts --header 'Authorization: Bearer ${{ inputs.token }}'"
        fi

        # Set curl params to get latest release data of the build validation scripts
        curlParamsGetLatestReleaseData="$curlOpts https://api.github.com/repos/gradle/gradle-enterprise-build-validation-scripts/releases/latest"

        # Get the download url of the latest release
        downloadUrl=$(eval curl $curlParamsGetLatestReleaseData | jq -c '.assets[] | select(.content_type == "application/zip")' | jq -r .browser_download_url | grep maven)

        # Set curl params to download the build validation scripts
        curlParamsDownloadScripts="$curlOpts --output gradle-enterprise-maven-build-validation.zip $downloadUrl"

        # Download the latest version of the build validation scripts
        eval curl $curlParamsDownloadScripts

        # Unzip the downloaded build validation scripts
        unzip -q -o gradle-enterprise-maven-build-validation.zip
      shell: bash
