name: Create Development Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  development_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          arguments: build githubRelease -i
