name: Create Development Release

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Enter the confirmation phrase 'DEVELOPMENT' (without quotes) if you are sure you want to trigger a development release.
        required: true

jobs:
  development_release:
    if: github.event.inputs.confirmation == 'DEVELOPMENT'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Build with Gradle
        run: ./gradlew build githubRelease -i
        env:
          GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
