name: Create Production Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: Enter the confirmation phrase 'PRODUCTION' (without quotes) if you are sure you want to trigger a release.
        required: true

jobs:
  production_release:
    if: github.event.inputs.confirmation == 'PRODUCTION'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up JDK 21
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
        with:
          develocity-access-key: ${{ secrets.DV_SOLUTIONS_ACCESS_KEY }}
      - name: Build with Gradle
        run: ./gradlew build githubRelease -PfinalRelease -i
        env:
          GITHUB_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
